### ISSUE TITLE
author - affiliation links

### ISSUE THREAD

**Issue by jcolomb** [ingmarboeschen/JATSdecoder#2]
Hello,

I am mostly pinging https://github.com/jam-schema/jams/issues/7 here, and will come back for more explanation when I have more time.

It seems you can get author names and affiliation, but the link between the two is lost (?).

I am asking with the idea to one day get author information from a paper to be "changed" into the jams format, and eventually used in other outputs (datasets, zenodo, citation.cff files,...)

**Comment by ingmarboeschen** [comment]
Dear Julian,
thanks for your request. Indeed, the link of author and affiliation is lost in my conversion of NISO-JATS as it is out of scope of my interests and (PMC) journals store this information quite heterogeneously, as you highlight it in your git.
Hope you still find a way and greetings from Hamburg
Ingmar
