### ISSUE TITLE
Is Python implementation in your future roadmap?

### ISSUE THREAD

**Issue by tomleung1996** [ingmarboeschen/JATSdecoder#3]
Hi Ingmar,

Thank you for your hard work on this wonderful tool. JATSdecoder is one of the best software I have used for scientific text mining! 

I am not sure if it is out of the scope of your roadmap, but can I expect to see a Python implementation of JATSdecoder in near future?

**Comment by ingmarboeschen** [comment]
Hey Tom,
thanks for the nice feedback and your questions. Right now I don't have the capacity to implement JATSdecoder in Python. 
Greetings
Ingmar
