### ISSUE TITLE
How can I seperate paragraphs in the main texts?

### ISSUE THREAD

**Issue by tomleung1996** [ingmarboeschen/JATSdecoder#4]
Hi Ingmar,

I tried JATSdecoder on a PLOS One XML document and would like to extract paragraphs from the main text. However, it seems that JATSdecoder only separates first-level sections (e.g., Introduction, Method, etc.) and all texts are stored in corresponding sections without paragraph information.

How can I separate paragraphs with the help of the JATSdecoder?

Thank you!

**Comment by ingmarboeschen** [comment]
Hey Tom,
you're right. I missed to specify the split pattern. This is how it should work without sentence vector
  a<-JATSdecoder("file.xml",paragraph=TRUE)$text
or better:
  a<-get.text(file.xml",paragraph=TRUE)$text
  lapply(a,function(x) strsplit(x," <New paragraph> "))
If you still want to convert the text of paragraphs to sentences, this would become a little too nested in my opinion...
Greetings
Ingmar

**Comment by tomleung1996** [comment]
Hi Ingmar,
It works great after your update! BTW, the initial response really confused me for a while XD.
I think I can use your sentence splitter in the abstract. It has done a great job.
Thank you very much!
