### ISSUE TITLE
can't parse a certain F statistic

### ISSUE THREAD

**Issue by alexholcombe** [ingmarboeschen/JATSdecoder#6]
Great resource, thank you!!
It seems  that JATSdecoder fails at extracting/checking the following:

` depth (F(22,440) = 0.649, p = 0.888, η2p = 0.031; BF10 = 0.002),`

whereas statcheck does extract and check it for consistency. This was based on upload the PDF to get-stats.app, so possibly PDF parsing is the problem but possibly not because it did well on the other stats in the PDF. Is it not set up for ANOVAS with df1 > 1?

**Comment by ingmarboeschen** [comment]
Hey Alex,
the stastistic are extracted well,  when I check your string in R with:
   JATSdecoder::get.stats("depth (F(22,440) = 0.649, p = 0.888, η2p = 0.031; BF10 = 0.002),")
It might be, that the pdf compilation failed at this part of your PDF. You could check that with a local installation of CERMINE on your machine or the online version: http://cermine.ceon.pl/index.html
Greetings from Hamburg
Ingmar

**Comment by alexholcombe** [comment]
ok, good to know this works, thank you, and thank you for the package!
